### ISSUE TITLE
consulta por consumidor final

### ISSUE THREAD

**Issue by ximiodev** [multinexo/php-afip-ws#18]
Hola, quisiera saber como realizar una FE con Wsmtxca para consumidor final. En algunos lados indican que el codigoDocumento dbería ser 99 y el doc 0, sin embargo para este servicio me indica que solo puedo usar los valores de codigoDocumento que existen para Wsmtxca, lo cual pude traerlos pero ninguno de ellos tiene el codigo 99. 
Alguien sabe como se haría?
Gracias!

**Comment by smblanco** [comment]
Solucionaste esto? yo lo corregí cualquier cosa contáctame

**Comment by ch31083** [comment]
Hola @smblanco, ¿qué código de documento estás utilizando? Me encuentro con la misma duda.

**Comment by pablorsk** [comment]
Al momento de [emitir una factura electrónica en Afip con Multinexo](https://multinexo.com/)...

Para
* **Consumidor final**
* Utilizando **Wsmtxca**

Se envía

* `codigoDocumento=99` (Sin identificar/venta global diaria)

Más tipos de documento en la API: https://api.multinexo.com/v1/identifications
